server:
  mem_limit: 4g
  image: alexanderilyin/docker-teamcity-server
  expose:
   - "8111"
  volumes:
    - .TeamCity:/root/.BuildServer
  links:
   - mysql
mysql:
  image: alexanderilyin/docker-mysql
  volumes:
    - .MySQL:/var/lib/mysql
  environment:
    MYSQL_DATABASE: teamcity
    MYSQL_USER: teamcity
    MYSQL_PASSWORD: teamcity
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
agent:
  privileged: true
  image: alexanderilyin/docker-teamcity-agent
  command: -u 'http://server:8111/'
  links:
   - server
nginx:
  image: quay.io/aptible/nginx
  environment:
    - UPSTREAM_SERVERS=server:8111
    - FORCE_SSL=true
  links:
    - server
  ports:
    - 443:443
    - 80:80
